import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { format } from 'date-fns'
import { EXPENSE_CATEGORIES, SAVINGS_TYPES } from '@/lib/constants'
import type { ReportData } from '@/types'

export function generatePDFReport(data: ReportData): Blob {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // Header
  doc.setFontSize(24)
  doc.setTextColor(99, 102, 241) // Primary indigo
  doc.text('MyWealth', pageWidth / 2, 20, { align: 'center' })

  doc.setFontSize(12)
  doc.setTextColor(100, 100, 100)
  doc.text('Personal Finance Report', pageWidth / 2, 28, { align: 'center' })

  // Period
  doc.setFontSize(10)
  doc.setTextColor(60, 60, 60)
  const periodText = `${format(data.period.start, 'MMM d, yyyy')} - ${format(data.period.end, 'MMM d, yyyy')}`
  doc.text(periodText, pageWidth / 2, 36, { align: 'center' })

  // Summary Section
  let yPos = 50
  doc.setFontSize(14)
  doc.setTextColor(30, 30, 30)
  doc.text('Financial Summary', 14, yPos)

  yPos += 10
  autoTable(doc, {
    startY: yPos,
    head: [['Category', 'Amount (UGX)']],
    body: [
      ['Total Expenses', formatNumber(data.summary.totalExpenses)],
      ['Total Savings', formatNumber(data.summary.totalSavings)],
      ['Total Income', formatNumber(data.summary.totalIncome)],
      ['Net Change', formatNumber(data.summary.netChange)],
    ],
    theme: 'striped',
    headStyles: { fillColor: [99, 102, 241] },
    styles: { fontSize: 10 },
  })

  // Expenses by Category
  yPos = (doc as any).lastAutoTable.finalY + 15
  doc.setFontSize(14)
  doc.text('Expenses by Category', 14, yPos)

  yPos += 10
  const expenseRows = data.charts.expensesByCategory.map((item) => [
    EXPENSE_CATEGORIES[item.category as keyof typeof EXPENSE_CATEGORIES]?.label || item.category,
    formatNumber(item.total),
    `${item.percentage}%`,
  ])

  autoTable(doc, {
    startY: yPos,
    head: [['Category', 'Amount (UGX)', 'Percentage']],
    body: expenseRows,
    theme: 'striped',
    headStyles: { fillColor: [99, 102, 241] },
    styles: { fontSize: 9 },
  })

  // Savings Goals
  if (data.savings.length > 0) {
    yPos = (doc as any).lastAutoTable.finalY + 15
    doc.setFontSize(14)
    doc.text('Savings Goals', 14, yPos)

    yPos += 10
    const savingsRows = data.savings.map((item) => [
      item.name,
      SAVINGS_TYPES[item.type as keyof typeof SAVINGS_TYPES]?.label || item.type,
      formatNumber(item.goalAmount),
      formatNumber(item.amountSaved),
      `${item.progress}%`,
    ])

    autoTable(doc, {
      startY: yPos,
      head: [['Name', 'Type', 'Goal (UGX)', 'Saved (UGX)', 'Progress']],
      body: savingsRows,
      theme: 'striped',
      headStyles: { fillColor: [16, 185, 129] },
      styles: { fontSize: 9 },
    })
  }

  // Expense Transactions
  if (data.expenses.length > 0) {
    yPos = (doc as any).lastAutoTable.finalY + 15

    // Check if we need a new page
    if (yPos > 250) {
      doc.addPage()
      yPos = 20
    }

    doc.setFontSize(14)
    doc.text('Expense Transactions', 14, yPos)

    yPos += 10
    const expenseTransactionRows = data.expenses.slice(0, 30).map((item) => [
      item.date,
      item.category,
      item.description || '-',
      formatNumber(item.amount),
    ])

    autoTable(doc, {
      startY: yPos,
      head: [['Date', 'Category', 'Description', 'Amount (UGX)']],
      body: expenseTransactionRows,
      theme: 'striped',
      headStyles: { fillColor: [239, 68, 68] },
      styles: { fontSize: 8 },
    })
  }

  // Footer
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Generated by MyWealth on ${format(new Date(), 'MMM d, yyyy')} - Page ${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    )
  }

  return doc.output('blob')
}

export function generateCSVReport(data: ReportData): Blob {
  const lines: string[] = []

  // Header
  lines.push('MyWealth Personal Finance Report')
  lines.push(`Period: ${format(data.period.start, 'MMM d, yyyy')} - ${format(data.period.end, 'MMM d, yyyy')}`)
  lines.push('')

  // Summary
  lines.push('=== FINANCIAL SUMMARY ===')
  lines.push('Category,Amount (UGX)')
  lines.push(`Total Expenses,${data.summary.totalExpenses}`)
  lines.push(`Total Savings,${data.summary.totalSavings}`)
  lines.push(`Total Income,${data.summary.totalIncome}`)
  lines.push(`Net Change,${data.summary.netChange}`)
  lines.push('')

  // Expenses by Category
  lines.push('=== EXPENSES BY CATEGORY ===')
  lines.push('Category,Amount (UGX),Percentage')
  data.charts.expensesByCategory.forEach((item) => {
    const label = EXPENSE_CATEGORIES[item.category as keyof typeof EXPENSE_CATEGORIES]?.label || item.category
    lines.push(`"${label}",${item.total},${item.percentage}%`)
  })
  lines.push('')

  // Savings Goals
  if (data.savings.length > 0) {
    lines.push('=== SAVINGS GOALS ===')
    lines.push('Name,Type,Goal (UGX),Saved (UGX),Progress')
    data.savings.forEach((item) => {
      const type = SAVINGS_TYPES[item.type as keyof typeof SAVINGS_TYPES]?.label || item.type
      lines.push(`"${item.name}","${type}",${item.goalAmount},${item.amountSaved},${item.progress}%`)
    })
    lines.push('')
  }

  // Expense Transactions
  if (data.expenses.length > 0) {
    lines.push('=== EXPENSE TRANSACTIONS ===')
    lines.push('Date,Category,Description,Amount (UGX)')
    data.expenses.forEach((item) => {
      lines.push(`${item.date},"${item.category}","${item.description || ''}",${item.amount}`)
    })
  }

  const csvContent = lines.join('\n')
  return new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
}

function formatNumber(num: number): string {
  return new Intl.NumberFormat('en-UG').format(num)
}
